#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: Mirror repo to GitLab

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  secrets: read

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  to_gitlab:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75 # v1
        with:
          target_repo_url: git@gitlab.com:${{ github.repository }}-mirror.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
