#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: Mirror repo to GitLab

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  secrets: read

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  to_gitlab:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@6dcf11b59156c6e0fc6a6b553ce204629f60a3cb # tag=v1
        with:
          target_repo_url: git@gitlab.com:${{ github.repository }}-mirror.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
